import Team from '../../Views/Home/Administration/TeamView/Team.View';
import BusinessGroupsView from '../../Views/Home/Administration/BusinessGroupsView/BusinessGroups.View';
import { LookupsLayout } from '../../Layouts/Home/LookupsLayout/LookupsLayout';
// import { ContactsLayout } from '../../Layouts/Home/Contacts/ContactsLayout';
import { PortfolioLayout } from '../../Layouts/Home/PortfolioLayout/PortfolioLayout';
import { UserView } from '../../Views/Home/Administration/UsersView';
import { BranchesLayout } from '../../Layouts/Home/BranchesLayout/BranchesLayout';
import { FormBuilderLayout } from '../../Layouts/Home/FormBuilder/FormBuilderLayout';
import { RolesLayout } from '../../Layouts/Home/RolesLayout/RolesLayout';
import { LeadsLayout } from '../../Layouts/Home/Leads/LeadsLayout';
import { UnitsSalesLayout } from '../../Layouts/Home/UnitsSalesLayout/UnitsSalesLayout';
import { UnitsLeaseLayout } from '../../Layouts/Home/UnitsLeaseLayout/UnitsLeaseLayout';
import { LeadsSalesLayout } from '../../Layouts/Home/LeadsSalesLayout/LeadsSalesLayout';
import { LeadsPropertyManagementLayout } from '../../Layouts/Home/LeadsPropertyManagementLayout/LeadsPropertyManagementLayout';
import { LeadsLeaseLayout } from '../../Layouts/Home/LeadsLeaseLayout/LeadsLeaseLayout';
import { ActivitiesSalesView } from '../../Views/Home/ActivitiesSalesView/ActivitiesSalesView';
import { OperatingCostsLayout } from '../../Layouts/Home/OperatingCostsLayout/OperatingCostsLayout';
import { QAView } from '../../Views/Home/QAView/QAView';
import {
  ImportDetailsView,
  UserManagementView,
  ActivitiesView,
  ActivitiesLeaseView,
  MonthlyCalendarView,
  MyLeadsView,
  MyReferralsView,
  SalesAvailabilityView,
  LeasingAvailabilityView,
} from '../../Views/Home';
import {
  ContactsPermissions, UserLoginPermissions, BusinessGroupsPermissions,
  TeamPermissions,
  RolesPermissions, ImageGalleryPermissions,
  ReportsPermissions,
  LocationsPermissions,
  AdminDashboardPermissions,
  TeamLeadDashboardPermissions,
  AgentDashboardPermissions , 
  BranchesPermissions
} from '../../Permissions';
import {
  PortfolioPermissions,
  PropertyManagementListPermissions,
  UnitPermissions,
  OperatingCostsPermissions,
  MaintenanceContractsPermissions,
  LeadsPermissions,
  IncidentsPermissions,
  AssetsPermissions,
  ActivitesPermissions,
  WorkOrdersPermissions
} from '../../Permissions/PropertyManagement';

import { WorkOrdersLayout } from '../../Layouts/Home/WorkOrdersLayout/WorkOrdersLayout';
import { IncidentsLayout } from '../../Layouts/Home/IncidentsLayout/IncidentsLayout';
import { AssetsLayout } from '../../Layouts/Home/AssetsLayout/AssetsLayout';
import { MaintenanceContractsLayout } from '../../Layouts/Home/MaintenanceContractsLayout/MaintenanceContractsLayout';
import { SalesTransactionsLayout } from '../../Layouts/Home/SalesTransactionsLayout/SalesTransactionsLayout';
import { LeasingTransactionsLayout } from '../../Layouts/Home/LeasingTransactionsLayout/LeasingTransactionsLayout';
import { InvoicesLayout } from '../../Layouts/Home/InvoicesLayout/InvoicesLayout';
import { PropertiesLayout } from '../../Layouts/Home/Properties/PropertiesLayout';
import { UnitsPropertyManagementLayout } from '../../Layouts/Home/UnitsPropertyManagement/UnitsPropertyManagement';
import { TemplatesLayout } from '../../Layouts/Home/TemplatesLayout/TemplatesLayout';
import { ContactsCrmLayout } from '../../Layouts/Home/ContactsCrmLayout/ContactsCrmLayout';
import { PropertiesCrmLayout } from '../../Layouts/Home/PropertiesCrmLayout/PropertiesCrmLayout';
import { GalleryCityLayout } from '../../Layouts/Home/CityLayout/CityLayout';
import { GalleryDistrictLayout } from '../../Layouts/Home/DistrictLayout/DistrictLayout';
import { GalleryCommunityLayout } from '../../Layouts/Home/CommunityLayout/CommunityLayout';
import { GallerySubCommunityLayout } from '../../Layouts/Home/SubCommunityLayout/SubCommunityLayout';
import { PropertiesPermissionsCRM } from '../../Permissions/PropertiesPermissions';
import { AgentsView } from '../../Views/Home/AgentsView/AgentsView';
import { AgentsRotationCriteriaLayout } from '../../Layouts/Home/AgentsRotationCriteriaLayout/AgentsRotationCriteriaLayout';
import { ReportsCRMLayout } from '../../Layouts/Home/ReportsLayout/ReportsCRMLayout';

import { ActivitiesTypeView } from '../../Views/Home/ActivitiesTypeView';
import {
  ActivitiesSalesPermissions,
  LeadsSalesPermissions,
  UnitsSalesPermissions,
} from '../../Permissions/Sales';
import {
  SalesTransactionsPermissions,
  LeasingTransactionsPermissions,
  InvoicesPermissions,
} from '../../Permissions/Accounts';
import {
  ActivitiesLeasePermissions,
  UnitsLeasePermissions,
  LeadsLeasePermissions,
} from '../../Permissions/Lease';
import {
  LeadsCAllCenterPermissions,
  ActivitiesCallCenterPermissions,
  QACallCenterPermissions
} from '../../Permissions/CallCenter';
import { CountryLayout } from '../../Layouts/Home/CountryLayout/CountryLayout';
import { CitysLayout } from '../../Layouts/Home/CitysLayout/CitysLayout';
import { DistrictsLayout } from '../../Layouts/Home/DistrictsLayout/DistrictsLayout';
import { CommunitiesLayout } from '../../Layouts/Home/CommunitiesLayout/CommunitiesLayout';
import { SubCommunitiesLayout } from '../../Layouts/Home/SubCommunitiesLayout/SubCommunitiesLayout';
import { AgentsPermissions, RotationSchemaPermissions } from '../../Permissions/AgentManagementPermissions';
import {
  LookupsPermissions, ActivityTypePermissions, TemplatesPermissions, FormBuilderPermissions
} from '../../Permissions/SystemParametersPermissions';
import { DashboardLayout } from '../../Layouts/Home/DashboardLayout/DashboardLayout';
import { AgentDashboard } from '../../Views/Home/Dashboard/AgentDashboard/AgentDashboard';
import { TeamleadDashboard } from '../../Views/Home/Dashboard/TeamleadDashboard/TeamleadDashboard';
 import { ExceptionPermissionsHelper } from '../../Helper/ExceptionPermissions.Helper';
import { LeaseListingTeamlead } from '../../Views/Home/Dashboard/LeaseListingTeamlead/LeaseListingTeamlead';
import { LeasingTeamLead } from '../../Views/Home/Dashboard/LeasingTeamLead/LeasingTeamLead';
import { SalesListingTeamlead } from '../../Views/Home/Dashboard/SalesListingTeamlead/SalesListingTeamlead';
import { AgentSalesListing } from '../../Views/Home/Dashboard/AgentSalesListing';
import { AgentLeaseListing } from '../../Views/Home/Dashboard/AgentLeaseListing';

 const contactExceptionPermission = ExceptionPermissionsHelper() || false;

export const HomeRoutes = [
  {
    id: 10,
    path: '/leads',
    name: 'LeadsView:leads',
    component: LeadsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(LeadsCAllCenterPermissions),
    groupId: 2,
    order: 1,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'LeadsView:leads',
        isDisabled: false,
        route: '/home/leads',
        groupName: 'call-center',
      },
    ],
  },

  {
    id: 30,
    path: '/add',
    name: 'Administration.Users.UsersManagementView.add-new-user',
    component: UserManagementView,
    layout: '/home/Users',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(UserLoginPermissions),
    isDisabled: false,
    showInMenu: false,
    isExact: true,
    breadcrumbs: [
      {
        name: 'SideMenuView.Administration.Users',
        isDisabled: false,
        route: '/home/Users',
        groupName: 'system-admin',
      },
      {
        name: 'UsersView:UsersManagementView.add-new-user',
        isDisabled: false,
        route: '/home/Users/add',
      },
    ],
  },
  {
    id: 30,
    path: '/edit',
    name: 'UsersView:UsersManagementView.edit-user',
    component: UserManagementView,
    layout: '/home/Users',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(UserLoginPermissions),
    isDisabled: false,
    showInMenu: false,
    isExact: true,
    breadcrumbs: [
      {
        name: 'SideMenuView.Administration.Users',
        isDisabled: false,
        route: '/home/Users',
        groupName: 'system-admin',
      },
      {
        name: 'UsersView:UsersManagementView.edit-user',
        isDisabled: false,
        route: '/home/Users/edit',
      },
    ],
  },
  {
    id: 30,
    path: '/Users',
    name: 'SideMenuView.Administration.Users',
    component: UserView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(UserLoginPermissions),
    groupId: 4,
    order: 1,
    icon: 'mdi mdi-badge-account-outline',
    iconActive: 'mdi mdi-badge-account',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'SideMenuView.Administration.Users',
        isDisabled: false,
        route: '/home/Users',
        groupName: 'system-admin',
      },
    ],
  },
  // {
  //   id: 33,
  //   path: '/Administration/UserDataView',
  //   name: 'SideMenuView.Administration.UsersDataViewing',
  //   component: UserDataViewLayout,
  //   layout: '/home',
  //   default: false,
  //   isRoute: true,
  //   authorize: true,
  //   roles: [],
  //   groupId: 4,
  //   order: 2,
  //   icon: 'mdi mdi-view-list-outline',
  //   iconActive: 'mdi mdi-view-list-outline c-primary',
  //   isDisabled: false,
  //   showInMenu: true,
  //   isExact: false,
  //   breadcrumbs: [],
  // },
  {
    id: 31,
    path: '/Administration/BusinessGroups',
    name: 'SideMenuView.Administration.BusinessGroups',
    component: BusinessGroupsView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(BusinessGroupsPermissions),
    groupId: 4,
    order: 3,
    icon: 'mdi mdi-file-tree-outline',
    iconActive: 'mdi mdi-file-tree-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: true,
    breadcrumbs: [
      {
        name: 'SideMenuView.Administration.BusinessGroups',
        isDisabled: false,
        route: '/home/Administration/BusinessGroups',
        groupName: 'system-admin',
      },
    ],
  },
  {
    id: 33,
    path: '/Roles',
    name: 'SideMenuView.Administration.Roles',
    component: RolesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(RolesPermissions),
    groupId: 4,
    order: 8,
    icon: 'mdi mdi-checkbox-multiple-marked',
    iconActive: 'mdi mdi-checkbox-multiple-marked c-primary',
    // routerLink: '/home/contacts',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [],
  },

  {
    id: 32,
    path: '/Administration/Team',
    name: 'SideMenuView.Administration.Team',
    component: Team,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(TeamPermissions),
    groupId: 4,
    order: 3,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'SideMenuView.Administration.Team',
        isDisabled: false,
        route: '/home/Administration/Team',
        groupName: 'system-admin',
      },
    ],
  },
  {
    id: 11,
    path: '/Activities',
    name: 'SideMenuView.ActivitiesView.ActivitiesView',
    component: ActivitiesView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(ActivitiesCallCenterPermissions),
    groupId: 2,
    order: 2,
    icon: 'mdi mdi-format-list-checks c-white',
    iconActive: 'mdi mdi-format-list-checks c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'SideMenuView.ActivitiesView.ActivitiesView',
        isDisabled: false,
        route: '/home/Activities',
        groupName: 'call-center',
      },
    ],
  },
  {
    id: 41,
    path: '/QA',
    name: 'SideMenuView.QAView.QAView',
    component: QAView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(QACallCenterPermissions),
    groupId: 2,
    order: 3,
    icon: 'mdi mdi-language-xaml c-white',
    iconActive: 'mdi mdi-language-xaml c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'SideMenuView.QAView.QAView',
        isDisabled: false,
        route: '/home/QA',
        groupName: 'call-center',
      },
    ],
  },
  {
    id: 21,
    path: '/portfolio',
    name: 'PortfolioView:portfolio',
    component: PortfolioLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(PortfolioPermissions)],
    groupId: 11,
    order: 7,
    icon: 'mdi mdi-domain c-white',
    iconActive: 'mdi mdi-domain c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'PortfolioView:portfolio',
        isDisabled: false,
        route: '/home/portfolio',
        groupName: 'property-management',
      },
    ],
  },
  {
    id: 15,
    path: '/work-orders',
    name: 'WorkOrdersView:work-orders',
    component: WorkOrdersLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(WorkOrdersPermissions)],
    groupId: 11,
    order: 4,
    icon: 'mdi mdi-domain c-white',
    iconActive: 'mdi mdi-domain c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'WorkOrdersView:work-orders',
        isDisabled: false,
        route: '/home/work-orders',
        groupName: 'property-management',
      },
    ],
  },
  {
    id: 37,
    path: '/FormBuilder',
    name: 'SideMenuView.FormBuilder',
    component: FormBuilderLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(FormBuilderPermissions)],
    groupId: 16,
    order: 10,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [],
  },
  {
    id: 90,
    path: '/import-details',
    name: 'ImportDetailsView:import-details',
    component: ImportDetailsView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [],
    groupId: 2,
    order: 3,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: false,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ImportDetailsView:import-details',
        isDisabled: false,
        route: '/home/import-details',
      },

    ],
  },
  {
    id: 4,
    path: '/units-sales',
    name: 'UnitsView:units',
    component: UnitsSalesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(UnitsSalesPermissions),
    groupId: 6,
    order: 1,
    icon: 'mdi mdi-home-outline c-white',
    iconActive: 'mdi mdi-home-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [],
  },
  {
    id: 7,
    path: '/units-lease',
    name: 'UnitsView:units',
    component: UnitsLeaseLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(UnitsLeasePermissions),
    groupId: 7,
    order: 3,
    icon: 'mdi mdi-home-outline c-white',
    iconActive: 'mdi mdi-home-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [],
  },
  {
    id: 5,
    path: '/lead-sales',
    name: 'LeadsView:leads',
    component: LeadsSalesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(LeadsSalesPermissions),
    groupId: 6,
    order: 2,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [],
  },
  {
    id: 8,
    path: '/lead-lease',
    name: 'LeadsView:leads',
    component: LeadsLeaseLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(LeadsLeasePermissions),
    groupId: 7,
    order: 4,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [],
  },
  {
    id: 6,
    path: '/activities-sales',
    name: 'ActivitiesView:activities',
    component: ActivitiesSalesView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(ActivitiesSalesPermissions),
    groupId: 6,
    order: 3,
    icon: 'mdi mdi-format-list-checks c-white',
    iconActive: 'mdi mdi-format-list-checks c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ActivitiesView:activities',
        isDisabled: false,
        route: '/home/activities-sales',
        groupName: 'sales',
      },
    ],
  },

  {
    id: 9,
    path: '/activities-lease',
    name: 'ActivitiesView:activities',
    component: ActivitiesLeaseView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(ActivitiesLeasePermissions),
    groupId: 7,
    order: 5,
    icon: 'mdi mdi-format-list-checks c-white',
    iconActive: 'mdi mdi-format-list-checks c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ActivitiesView:activities',
        isDisabled: false,
        route: '/home/activities-lease',
        groupName: 'leasing',
      },
    ],
  },

  {
    id: 22,
    path: '/activities-management',
    name: 'ActivitiesView:activities',
    component: ActivitiesView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(ActivitesPermissions)],
    groupId: 11,
    order: 7,
    icon: 'mdi mdi-format-list-checks c-white',
    iconActive: 'mdi mdi-format-list-checks c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ActivitiesView:activities',
        isDisabled: false,
        route: '/home/activities-management',
        groupName: 'property-management',
      },
    ],
  },

  {
    id: 17,
    path: '/Incidents',
    name: 'IncidentsView:Incidents',
    component: IncidentsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(IncidentsPermissions)],
    groupId: 11,
    order: 5,
    icon: 'mdi mdi-domain c-white',
    iconActive: 'mdi mdi-domain c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'WorkOrdersView:Incidents',
        isDisabled: false,
        route: '/home/Incidents',
        groupName: 'property-management',
      },
    ],
  },
  {
    id: 16,
    path: '/operating-costs',
    name: 'OperatingCostsView:operating-costs',
    component: OperatingCostsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(OperatingCostsPermissions)],
    groupId: 11,
    order: 4,
    icon: 'mdi mdi-format-list-checks c-white',
    iconActive: 'mdi mdi-format-list-checks c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'OperatingCostsView:operating-costs',
        isDisabled: false,
        route: '/home/operating-costs',
        groupName: 'property-management',
      },
    ],
  },
  {
    id: 20,
    path: '/assets',
    name: 'AssetsView:assets',
    component: AssetsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(AssetsPermissions)],
    groupId: 11,
    order: 6,
    icon: 'mdi mdi-domain c-white',
    iconActive: 'mdi mdi-domain c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'AssetsView:assets',
        isDisabled: false,
        route: '/home/assets',
        groupName: 'property-management',
      },
    ],
  },
  {
    id: 18,
    path: '/Maintenance-Contracts',
    name: 'MaintenanceContracts:Maintenance-Contracts',
    component: MaintenanceContractsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(MaintenanceContractsPermissions)],
    groupId: 11,
    order: 5,
    icon: 'mdi mdi-domain c-white',
    iconActive: 'mdi mdi-domain c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'MaintenanceContracts:Maintenance-Contracts',
        isDisabled: false,
        route: '/home/MaintenanceContractsView',
        groupName: 'property-management',
      },
    ],
  },
  {
    id: 23,
    path: '/sales-transactions',
    name: 'SalesTransactionsView:sales-transactions',
    component: SalesTransactionsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(SalesTransactionsPermissions)],
    groupId: 12,
    order: 1,
    isDisabled: false,
    icon: 'mdi mdi-currency-usd c-blue-lighter',
    iconActive: 'mdi mdi-currency-usd c-white',
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'SalesTransactionsView:sales-transactions',
        isDisabled: false,
        route: '/home/sales-transactions/view',
        groupName: 'accounts',
      },
    ],
  },
  {
    id: 24,
    path: '/leasing-transactions',
    name: 'LeasingTransactionsView:leasing-transactions',
    component: LeasingTransactionsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(LeasingTransactionsPermissions)],
    groupId: 12,
    order: 2,
    icon: 'mdi mdi-account-key-outline c-blue-lighter',
    iconActive: 'mdi mdi-account-key-outline c-white',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'LeasingTransactionsView:leasing-transactions',
        isDisabled: false,
        route: '/home/leasing-transactions/view',
        groupName: 'accounts',
      },
    ],
  },
  {
    id: 25,
    path: '/invoices',
    name: 'InvoicesView:invoices',
    component: InvoicesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(InvoicesPermissions)],
    groupId: 12,
    order: 2,
    icon: 'mdi mdi-receipt c-blue-lighter',
    iconActive: 'mdi mdi-receipt c-white',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'InvoicesView:invoices',
        isDisabled: false,
        route: '/home/invoices/view',
        groupName: 'accounts',
      },
    ],
  },

  {
    id: 12,
    path: '/properties',
    name: 'PropertiesView:properties',
    component: PropertiesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(PropertyManagementListPermissions)],
    groupId: 11,
    order: 2,
    icon: 'mdi mdi-domain c-white',
    iconActive: 'mdi mdi-domain c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'PropertiesView:properties',
        isDisabled: false,
        route: '/home/properties',
        groupName: 'property-management',
      },
    ],
  },
  {
    id: 13,
    path: '/units-property-management',
    name: 'UnitsView:units',
    component: UnitsPropertyManagementLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(UnitPermissions)],
    groupId: 11,
    order: 3,
    icon: 'mdi mdi-home-outline c-white',
    iconActive: 'mdi mdi-home-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'UnitsView:units',
        isDisabled: false,
        route: '/home/units-property-management/view',
        groupName: 'property-management',
      },
    ],
  },
  {
    id: 89,
    path: '/monthly-calendar-view',
    name: 'MonthlyCalendarView:monthly-calendar-view',
    component: MonthlyCalendarView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [],
    groupId: 11,
    order: 3,
    icon: 'mdi mdi-home-outline c-white',
    iconActive: 'mdi mdi-home-outline c-primary',
    isDisabled: false,
    showInMenu: false,
    isExact: false,
    breadcrumbs: [
      {
        name: 'MonthlyCalendarView:monthly-calendar-view',
        isDisabled: false,
        route: '/home/monthly-calendar-view',
      },
    ],
  },
  {
    id: 14,
    path: '/Leads-property-management',
    name: 'LeadsView:leads',
    component: LeadsPropertyManagementLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(LeadsPermissions)],
    groupId: 11,
    order: 3,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [],
  },
  {
    id: 86,
    path: '/my-lead',
    name: 'MyLeadView:my-leads',
    component: MyLeadsView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [],
    groupId: 14,
    order: 1,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'MyLeadView:my-leads',
        isDisabled: false,
        route: '/home/my-lead',
        groupName: 'my-lead',
      },
    ],
  },
  {
    id: 83,
    path: '/my-referrals',
    name: 'MyReferralsView:my-referrals',
    component: MyReferralsView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [],
    groupId: 14,
    order: 2,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'MyReferralsView:my-referrals',
        isDisabled: false,
        route: '/home/my-referrals',
        groupName: 'my-lead',
      },
    ],
  },
  {
    id: 82,
    path: '/sales-availability',
    name: 'SalesAvailabilityView:sales-availability',
    component: SalesAvailabilityView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [],
    groupId: 14,
    order: 3,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'SalesAvailabilityView:sales-availability',
        isDisabled: false,
        route: '/home/sales-availability',
        groupName: 'my-lead',
      },
    ],
  },
  {
    id: 81,
    path: '/leasing-availability',
    name: 'LeasingAvailabilityView:leasing-availability',
    component: LeasingAvailabilityView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [],
    groupId: 14,
    order: 4,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'LeasingAvailabilityView:leasing-availability',
        isDisabled: false,
        route: '/home/leasing-availability',
        groupName: 'my-lead',
      },
    ],
  },
  {
    id: 1,
    path: '/Contacts-CRM',
    name: 'ContactsView:contacts',
    component: ContactsCrmLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(ContactsPermissions),
    groupId: 15,
    order: 1,
    icon: 'mdi mdi-account-group-outline c-white',
    iconActive: 'mdi mdi-account-group-outline c-primary',
    isDisabled: false,
    showInMenu: !contactExceptionPermission,
   // showInMenu:true ,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ContactsView:contacts',
        isDisabled: false,
        route: '/home/contacts-crm',
        groupName: 'crm',
      },
    ],
  },
  {
    id: 2,
    path: '/Properties-CRM',
    name: 'PropertiesView:properties',
    component: PropertiesCrmLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(PropertiesPermissionsCRM),
    groupId: 15,
    order: 2,
    icon: 'mdi mdi-domain c-white',
    iconActive: 'mdi mdi-domain c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'PropertiesView:properties',
        isDisabled: false,
        route: '/home/Properties-CRM',
        groupName: 'crm',
      },
    ],
  },
  {
    id: 3,
    path: '/Reports-CRM',
    name: 'Reports:reports',
    component: ReportsCRMLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(ReportsPermissions),
    groupId: 15,
    order: 3,
    icon: 'mdi mdi-view-list-outline c-white',
    iconActive: 'mdi mdi-view-list-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'Reports:reports',
        isDisabled: false,
        route: '/home/Reports-CRM',
        groupName: 'crm',
      },
    ],
  },
  {
    id: 34,
    path: '/lookups',
    name: 'homeLayout.lookupsView.lookups',
    component: LookupsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(LookupsPermissions)],
    groupId: 16,
    order: 1,
    icon: 'mdi mdi-menu -multiple-marked',
    iconActive: 'mdi mdi-menu -multiple-marked c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'homeLayout.lookupsView.lookups',
        isDisabled: false,
        route: '/home/lookups',
        groupName: 'system-parameters',
      },
    ],
  },
  {
    id: 36,
    path: '/templates',
    name: 'TemplatesView:templates',
    component: TemplatesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(TemplatesPermissions)],
    groupId: 16,
    order: 2,
    icon: 'mdi mdi-newspaper-variant-multiple c-blue-lighter',
    iconActive: 'mdi mdi-newspaper-variant-multiple c-white',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'TemplatesView:templates',
        isDisabled: false,
        route: '/home/templates/view',
        groupName: 'system-parameters',
      },
    ],
  },

  {
    id: 26,
    path: '/city-gallery',
    name: 'ImagesGalleryGroup:city-gallery',
    component: GalleryCityLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-camera-image',
    iconActive: 'mdi mdi-camera-image',
    roles: Object.values(ImageGalleryPermissions),
    groupId: 17,
    order: 1,
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ImagesGalleryGroup:city-gallery',
        isDisabled: false,
        route: '/home/city-gallery/view',
        groupName: 'images-gallery',
      },
    ],
  },
  {
    id: 27,
    path: '/district-gallery',
    name: 'ImagesGalleryGroup:district-gallery',
    component: GalleryDistrictLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-file-image',
    iconActive: 'mdi mdi-file',
    roles: Object.values(ImageGalleryPermissions),
    groupId: 17,
    order: 2,
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ImagesGalleryGroup:district-gallery',
        isDisabled: false,
        route: '/home/district-gallery/view',
        groupName: 'images-gallery',
      },
    ],
  },
  {
    id: 28,
    path: '/community-gallery',
    name: 'ImagesGalleryGroup:community-gallery',
    component: GalleryCommunityLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-folder-multiple-image',
    iconActive: 'mdi mdi-folder-multiple-image',
    roles: Object.values(ImageGalleryPermissions),
    groupId: 17,
    order: 3,
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ImagesGalleryGroup:community-gallery',
        isDisabled: false,
        route: '/home/community-gallery/view',
        groupName: 'images-gallery',
      },
    ],
  },
  {
    id: 29,
    path: '/subCommunity-gallery',
    name: 'ImagesGalleryGroup:sub-community-gallery',
    component: GallerySubCommunityLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: Object.values(ImageGalleryPermissions),
    icon: 'mdi mdi-image-multiple',
    iconActive: 'mdi mdi-image-multiple',
    groupId: 17,
    order: 4,
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'ImagesGalleryGroup:sub-community-gallery',
        isDisabled: false,
        route: '/home/subCommunity-gallery/view',
        groupName: 'images-gallery',
      },
    ],
  },
  {
    id: 39,
    path: '/agent-management/Agents',
    name: 'agent',
    component: AgentsView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(AgentsPermissions)],
    groupId: 18,
    order: 1,
    icon: 'mdi mdi-google-street-view c-white',
    iconActive: 'mdi mdi-google-street-view c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'agent',
        isDisabled: false,
        route: '/home/agent-management',
        groupName: 'agent-management',
      },
    ],
  },
  {
    id: 40,
    path: '/rotation-criteria',
    name: 'Agents:rotation-schema',
    icon: 'mdi mdi-receipt c-white',
    iconActive: 'mdi mdi-receipt c-blue-dark',
    component: AgentsRotationCriteriaLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(RotationSchemaPermissions)],
    groupId: 18,
    order: 2,
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'Agents:rotation-schema',
        isDisabled: false,
        route: '/home/rotation-criteria/view',
        groupName: 'agent-management',
      },
    ],
  },
  {
    id: 35,
    path: '/activity-type',
    name: 'homeLayout.activity-type.activity-type',
    component: ActivitiesTypeView,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(ActivityTypePermissions)],
    groupId: 16,
    order: 1,
    icon: 'mdi mdi-upload-network',
    iconActive: 'mdi mdi-upload-network c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'homeLayout.activity-type.activity-type',
        isDisabled: false,
        route: '/home/activity-type',
        groupName: 'system-parameters',
      },
    ],
  },
  {
    id: 42,
    path: '/country',
    name: 'LocationView:country',
    component: CountryLayout,
    layout: '/home',
    default: false,
    icon: 'mdi mdi-map-marker-radius-outline',
    iconActive: 'mdi mdi-map-marker-radius',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(LocationsPermissions)],
    groupId: 19,
    order: 5,
    breadcrumbs: [
      {
        name: 'LocationView:country',
        isDisabled: false,
        route: '/home/country',
        groupName: 'locations',
      },
    ],
  },
  {
    id: 43,
    path: '/city',
    name: 'LocationView:city',
    component: CitysLayout,
    layout: '/home',
    icon: 'mdi mdi-map-marker-down',
    iconActive: 'mdi mdi-map-marker-down',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(LocationsPermissions)],
    groupId: 19,
    order: 5,
    breadcrumbs: [
      {
        name: 'LocationView:city',
        isDisabled: false,
        route: '/home/city',
        groupName: 'locations',
      },
    ],
  },
  {
    id: 46,
    path: '/District',
    name: 'LocationView:District',
    component: DistrictsLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(LocationsPermissions)],
    groupId: 19,
    order: 5,
    icon: 'mdi mdi-map-marker-multiple',
    iconActive: 'mdi mdi-map-marker-multiple',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'LocationView:District',
        isDisabled: false,
        route: '/home/District',
        groupName: 'locations',
      },
    ],
  },
  {
    id: 44,
    path: '/Communitie',
    name: 'LocationView:Communitie',
    component: CommunitiesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles: [...Object.values(LocationsPermissions)],
    groupId: 19,
    icon: 'mdi mdi-map-marker-distance',
    iconActive: 'mdi mdi-map-marker-distance',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    order: 5,
    breadcrumbs: [
      {
        name: 'LocationView:Communitie',
        isDisabled: false,
        route: '/home/Communitie',
        groupName: 'locations',
      },
    ],
  },
  {
    id: 45,
    path: '/SubCommunitie',
    name: 'LocationView:SubCommunitie',
    component: SubCommunitiesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-map-marker-path',
    iconActive: 'mdi mdi-map-marker-path',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(LocationsPermissions)],
    groupId: 19,
    order: 5,
    breadcrumbs: [
      {
        name: 'LocationView:SubCommunitie',
        isDisabled: false,
        route: '/home/SubCommunitie',
        groupName: 'locations',
      },
    ],

  },
  {
    id: 47,
    path: '/dashboard',
    name: 'Dashboard:admin-dashboard',
    component: DashboardLayout,
    layout: '/home',
    default: true,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-account-group-outline c-white',
    iconActive: 'mdi mdi-account-group-outline c-primary',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(AdminDashboardPermissions)],
    groupId: 1,
    order: 1,
    breadcrumbs: [
      {
        name: 'Dashboard:admin-dashboard',
        isDisabled: false,
        route: '/home/dashboard',
        groupName: 'Dashboard',
      },
    ],

  },
  {
    id: 48,
    path: '/agent-dashboard',
    name: 'Dashboard:agent-dashboard',
    component: AgentDashboard,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-google-street-view c-white',
    iconActive: 'mdi mdi-google-street-view c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(AgentDashboardPermissions)],
    groupId: 1,
    order: 6,
    breadcrumbs: [
      {
        name: 'Dashboard:agent-dashboard',
        isDisabled: false,
        route: '/home/dashboard',
        groupName: 'Dashboard',
      },
    ],

  },
  {
    id: 49,
    path: '/teamlead-dashboard',
    name: 'Dashboard:lease-listing-teamlead-dashboard',
    component: LeaseListingTeamlead,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(TeamLeadDashboardPermissions)],
    groupId: 1,
    order: 4,
    breadcrumbs: [
      {
        name: 'Dashboard:lease-listing-teamlead-dashboard',
        isDisabled: false,
        route: '/home/dashboard',
        groupName: 'Dashboard',
      },
    ],

  },
  {
    id: 51,
    path: '/sales-teamlead-dashboard',
    name: 'Dashboard:salesteamlead-dashboard',
    component: TeamleadDashboard,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(TeamLeadDashboardPermissions)],
    groupId: 1,
    order: 2,
    breadcrumbs: [
      {
        name: 'Dashboard:salesteamlead-dashboard',
        isDisabled: false,
        route: '/home/dashboard',
        groupName: 'Dashboard',
      },
    ],

  },
  {
    id: 52,
    path: '/lease-teamlead-dashboard',
    name: 'Dashboard:leaseteamlead-dashboard',
    component: LeasingTeamLead,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(TeamLeadDashboardPermissions)],
    groupId: 1,
    order: 3,
    breadcrumbs: [
      {
        name: 'Dashboard:leaseteamlead-dashboard',
        isDisabled: false,
        route: '/home/dashboard',
        groupName: 'Dashboard',
      },
    ],

  },
  {
    id: 52,
    path: '/saleslisting-teamlead',
    name: 'Dashboard:saleslistingteamlead-dashboard',
    component: SalesListingTeamlead,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(TeamLeadDashboardPermissions)],
    groupId: 1,
    order: 5,
    breadcrumbs: [
      {
        name: 'Dashboard:saleslistingteamlead-dashboard',
        isDisabled: false,
        route: '/home/dashboard',
        groupName: 'Dashboard',
      },
    ],

  },
  {
    id: 53,
    path: '/agentsaleslisting',
    name: 'Dashboard:agentsaleslisting-dashboard',
    component: AgentSalesListing,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(TeamLeadDashboardPermissions)],
    groupId: 1,
    order: 7,
    breadcrumbs: [
      {
        name: 'Dashboard:agentsaleslisting-dashboard',
        isDisabled: false,
        route: '/home/dashboard',
        groupName: 'Dashboard',
      },
    ],

  },
  {
    id: 54,
    path: '/agentleaselisting',
    name: 'Dashboard:agentleaselisting-dashboard',
    component: AgentLeaseListing,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    icon: 'mdi mdi-account-outline c-white',
    iconActive: 'mdi mdi-account-outline c-blue-dark',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    roles: [...Object.values(TeamLeadDashboardPermissions)],
    groupId: 1,
    order: 8,
    breadcrumbs: [
      {
        name: 'Dashboard:agentleaselisting-dashboard',
        isDisabled: false,
        route: '/home/dashboard',
        groupName: 'Dashboard',
      },
    ],

  },
  {
    id: 80,
    path: '/branches',
    name: 'Branches',
    component: BranchesLayout,
    layout: '/home',
    default: false,
    isRoute: true,
    authorize: true,
    roles:  [...Object.values(BranchesPermissions)],
    groupId: 4,
    order: 2,
    icon: 'mdi mdi-badge-account-outline',
    iconActive: 'mdi mdi-badge-account',
    isDisabled: false,
    showInMenu: true,
    isExact: false,
    breadcrumbs: [
      {
        name: 'Branches',
        isDisabled: false,
        route: '/home/branches',
        groupName: 'system-admin',
      },
    ],
  }
];
